name: Auto Update Rules

on:
  schedule:
    - cron: '0 16 * * *'  # UTC时间16点（北京时间0点）
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Run processing script
      run: python process_rules.py
      
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add source/
        if ! git diff --cached --quiet; then
          git commit -m "Auto update rules $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes to commit"
        fi
