name: Update Reject Rules

on:
  # 每天北京时间0点执行（UTC时间16:00）
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v2

      - name: 创建临时目录
        run: mkdir -p temp

      - name: 下载 adrules-surge.conf
        run: |
          curl -sL https://adrules.top/adrules-surge.conf -o temp/adrules-surge.conf

      - name: 提取 DOMAIN-KEYWORD 和 DOMAIN-WILDCARD 内容到 reject_extra.list
        run: |
          grep -E '^(DOMAIN-KEYWORD|DOMAIN-WILDCARD)' temp/adrules-surge.conf > temp/reject_extra.list

      - name: 处理 DOMAIN-SUFFIX 行（转换为 .example.com 格式）
        run: |
          grep '^DOMAIN-SUFFIX' temp/adrules-surge.conf | sed -E 's/^DOMAIN-SUFFIX,/\./' > temp/adrules_suffix_processed.txt

      - name: 下载并处理 reject.conf（去掉以 # 开头的行）
        run: |
          curl -sL https://ruleset.skk.moe/List/domainset/reject.conf -o temp/reject_skk.conf
          grep -v '^#' temp/reject_skk.conf > temp/reject_skk_processed.txt

      - name: 下载并处理 surge2.txt（去掉以 # 开头的行）
        run: |
          curl -sL https://anti-ad.net/surge2.txt -o temp/surge2.txt
          grep -v '^#' temp/surge2.txt > temp/surge2_processed.txt

      - name: 合并处理后的内容生成 reject.conf（去重）
        run: |
          cat temp/adrules_suffix_processed.txt temp/reject_skk_processed.txt temp/surge2_processed.txt | sort | uniq > source/reject.conf

      - name: 将 reject_extra.list 移动到 source 文件夹
        run: cp temp/reject_extra.list source/reject_extra.list

      - name: 配置 Git 用户信息
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: 提交更改到仓库
        run: |
          git add source/reject.conf source/reject_extra.list
          if ! git diff --cached --quiet; then
            git commit -m "Update reject rules files"
            git push
          else
            echo "No changes to commit."
          fi
