name: Daily Rules Update

on:
  schedule:
    - cron: '0 16 * * *'  # 北京时间每天0点（UTC时间16点）
  workflow_dispatch:

jobs:
  process-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: master

    # 处理 adrules.top 规则
    - name: Process adrules.top
      run: |
        # 下载原始文件
        curl -s https://adrules.top/adrules-surge.conf -o adrules.conf

        # 步骤1.(1) 删除注释行
        grep -v '^#' adrules.conf > adrules_processed.conf

        # 步骤1.(2) 提取 DOMAIN-KEYWORD/WILDCARD 规则
        grep -E 'DOMAIN-KEYWORD|DOMAIN-WILDCARD' adrules_processed.conf | sort -u > source/reject_extra.list

        # 步骤1.(3) 处理 DOMAIN-SUFFIX 规则
        grep 'DOMAIN-SUFFIX' adrules_processed.conf | \
        sed 's/DOMAIN-SUFFIX,$.*$/.\1/' | \
        sort -u > suffix_processed.list

    # 处理其他两个规则源
    - name: Process other sources
      run: |
        # 处理 skk.moe 规则
        curl -s https://ruleset.skk.moe/List/domainset/reject.conf -o skk.conf
        grep -v '^#' skk.conf > skk_processed.conf

        # 处理 anti-ad.net 规则
        curl -s https://anti-ad.net/surge2.txt -o antiad.conf
        grep -v '^#' antiad.conf > antiad_processed.conf

    # 合并规则并去重
    - name: Merge rules
      run: |
        # 合并步骤1.(3)和步骤2的内容
        cat suffix_processed.list skk_processed.conf antiad_processed.conf | \
        sort -u > source/reject.conf

    # 提交更新
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # 检查文件变化
        if [ -n "$(git status --porcelain)" ]; then
          git add source/
          git commit -m "Update rules: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin master
        else
          echo "No changes to commit"
        fi

    # 清理临时文件
    - name: Cleanup
      run: |
        rm -f adrules* skk* antiad* *.list *.conf
