name: Auto Update Rules

on:
  schedule:
    - cron: '0 16 * * *'  # UTC时间16点（北京时间0点）
  workflow_dispatch:

jobs:
  process-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Process adrules-surge.conf
      run: |
        # 下载并处理第一个规则源
        curl -s https://adrules.top/adrules-surge.conf -o adrules.conf
        
        # 提取 DOMAIN-KEYWORD/WILDCARD（直接输出到目标文件）
        grep -E '^(DOMAIN-KEYWORD|DOMAIN-WILDCARD)' adrules.conf > source/reject_extra.list
        
        # 处理 DOMAIN-SUFFIX（保留原始目录结构）
        grep '^DOMAIN-SUFFIX' adrules.conf | sed -e 's/DOMAIN-SUFFIX,\(.*\),.*/.\1/' > domain-suffix.tmp

    - name: Process other rulesets
      run: |
        # 处理第二个规则源（自动覆盖临时文件）
        curl -s https://ruleset.skk.moe/List/domainset/reject.conf | grep -v '^#' > skk.tmp
        
        # 处理第三个规则源（保留原始注释清理逻辑）
        curl -s https://anti-ad.net/surge2.txt | grep -v '^#' | grep -v '^\s*$' > antiad.tmp  # 额外过滤空行

    - name: Merge and deduplicate
      run: |
        # 合并并去重（确保最终文件格式统一）
        cat domain-suffix.tmp skk.tmp antiad.tmp | awk '!seen[$0]++' > source/reject.conf  # 使用 awk 去重更高效

    - name: Secure commit
      run: |
        # 仅提交目标文件（保护现有其他文件）
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # 精确添加需要更新的文件
        git add source/reject_extra.list
        git add source/reject.conf
        
        # 检查是否有实际变更
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin master
        fi
