name: Update Filter Rules

on:
  schedule:
    - cron: '0 16 * * *'  # 北京时间每天0点（UTC+8）
  workflow_dispatch:       # 允许手动触发

jobs:
  process-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        mkdir -p temp
        mkdir -p source

    # 处理 adrules.list
    - name: Process adrules.list
      run: |
        # 下载原始文件
        curl -sSfL https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list -o temp/adrules.raw

        # 清理注释和空行
        grep -v '^[[:space:]]*#' temp/adrules.raw | grep -v '^$' > temp/adrules_cleaned.tmp

        # 提取 DOMAIN-KEYWORD/WILDCARD
        grep -E '^(DOMAIN-KEYWORD|DOMAIN-WILDCARD),' temp/adrules_cleaned.tmp | \
        awk -F, '{print $2}' | \
        sort -u > source/reject_extra.list

        # 处理 DOMAIN-SUFFIX
        grep '^DOMAIN-SUFFIX,' temp/adrules_cleaned.tmp | \
        awk -F, '{print "."$2}' > temp/domain_suffix.tmp

    # 处理其他规则
    - name: Process other sources
      run: |
        # 处理 reject.conf
        curl -sSfL https://ruleset.skk.moe/List/domainset/reject.conf -o temp/reject.raw
        grep -v '^[[:space:]]*#' temp/reject.raw | grep -v '^$' > temp/reject_cleaned.conf

        # 处理 surge2.txt
        curl -sSfL https://anti-ad.net/surge2.txt -o temp/surge.raw
        grep -v '^[[:space:]]*#' temp/surge.raw | grep -v '^$' | \
        sed 's/DOMAIN-SUFFIX,//g' > temp/surge_cleaned.txt

    # 合并文件
    - name: Merge rules
      run: |
        cat temp/domain_suffix.tmp temp/reject_cleaned.conf temp/surge_cleaned.txt | \
        sort -u > source/reject.conf

    # 清理临时文件
    - name: Cleanup
      run: rm -rf temp

    # 提交变更
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        git add source/reject*.list source/reject.conf
        
        # 检查是否有实际变更
        if [[ $(git status --porcelain) ]]; then
          git commit -m "Update rules $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes detected"
        fi
