name: Update reject.conf

on:
  schedule:
    # 每天北京时间 0 点执行，UTC 时间为前一天16:00
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  update-reject-conf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v2

      - name: 配置 Git 用户信息
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: 下载、处理并合并文件
        run: |
          set -e
          # 创建临时目录
          mkdir temp && cd temp

          # 下载 adrules.list 并提取含 DOMAIN-SUFFIX 的行，
          # 将 "DOMAIN-SUFFIX," 替换为"."（确保每行开头为"."）
          curl -s -o adrules.list https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list
          grep "DOMAIN-SUFFIX," adrules.list | sed 's/DOMAIN-SUFFIX,/\./' > adrules_processed.txt

          # 下载 reject.conf 和 surge2.txt，并删除以 "#" 开头的行
          curl -s -o reject1.conf https://ruleset.skk.moe/List/domainset/reject.conf
          curl -s -o surge2.txt https://anti-ad.net/surge2.txt
          grep -v "^#" reject1.conf > reject1_processed.txt
          grep -v "^#" surge2.txt > surge2_processed.txt

          # 合并所有处理后的内容，去重（即使有重复只保留一个）
          cat adrules_processed.txt reject1_processed.txt surge2_processed.txt | sort -u > merged.txt

          # 统计行数，并在文件开头添加注释
          LINE_COUNT=$(wc -l < merged.txt)
          echo "# Total lines: ${LINE_COUNT}" > reject.conf
          cat merged.txt >> reject.conf

          # 将生成的文件移动到仓库的 source 文件夹中
          # 注意：source 文件夹已存在且可能有其他文件，覆盖重名文件
          mv reject.conf ../source/reject.conf

          # 返回上级目录并清理临时目录
          cd ..
          rm -rf temp

      - name: 提交并推送更改
        run: |
          git add source/reject.conf
          # 即使内容无变化也创建空提交，以覆盖原有文件
          git commit --allow-empty -m "Update reject.conf"
          git push origin master
