name: Update Filter Rules

on:
  schedule:
    - cron: '0 16 * * *' # 北京时间每天0点（UTC+8）
  workflow_dispatch:

jobs:
  process-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        # 创建临时工作目录
        mkdir -p temp
        mkdir -p source

    # [原有处理步骤保持不变...]
    # 处理第一个规则文件
    - name: Process adrules.list
      run: |
        # 下载文件并处理
        curl -sSfL https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list -o temp/adrules.list
        
        # (1) 删除注释
        grep -v '^#' temp/adrules.list > temp/adrules_cleaned.list
        
        # (2) 生成 reject_extra.list
        grep -E 'DOMAIN-KEYWORD|DOMAIN-WILDCARD' temp/adrules_cleaned.list | sort -u > source/reject_extra.list
        
        # (3) 处理 DOMAIN-SUFFIX
        grep 'DOMAIN-SUFFIX' temp/adrules_cleaned.list | \
        sed -E 's/DOMAIN-SUFFIX,(.*)/.\1/' > temp/domain_suffix.list

    # 处理其他规则文件
    - name: Process other rule sources
      run: |
        # 下载并处理 reject.conf
        curl -sSfL https://ruleset.skk.moe/List/domainset/reject.conf -o temp/reject.conf
        grep -v '^#' temp/reject.conf > temp/reject_cleaned.conf
        
        # 下载并处理 surge2.txt
        curl -sSfL https://anti-ad.net/surge2.txt -o temp/surge2.txt
        grep -v '^#' temp/surge2.txt > temp/surge_cleaned.txt

    # 合并并去重
    - name: Merge and deduplicate
      run: |
        # 合并所有域名规则
        cat temp/domain_suffix.list temp/reject_cleaned.conf temp/surge_cleaned.txt | \
        sort -u > source/reject.conf

    - name: Cleanup temporary files
      run: |
        # 显式删除临时目录
        rm -rf temp
        echo "临时目录已清理"

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # 添加目标文件到暂存区
        git add source/reject*.list source/reject.conf
        
        # 检查是否有实际变更
        if [[ $(git status --porcelain) ]]; then
          git commit -m "Update filter rules $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "没有检测到文件变更，跳过提交步骤"
        fi
