name: Update Reject Files

on:
  schedule:
    # 每天北京时间 0 点对应 UTC 16:00
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create source folder if not exists
        run: mkdir -p source

      - name: Download adrules.list
        run: |
          echo "Downloading adrules.list..."
          curl -sSL "https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list" -o adrules.list

      - name: Process adrules.list
        run: |
          echo "Removing comment lines from adrules.list..."
          grep -v '^#' adrules.list > adrules_no_comments.list || true

          echo "Extracting DOMAIN-KEYWORD and DOMAIN-WILDCARD lines to source/reject_extra.list..."
          grep -E 'DOMAIN-KEYWORD|DOMAIN-WILDCARD' adrules_no_comments.list > source/reject_extra.list || true

          echo "Extracting and processing DOMAIN-SUFFIX lines..."
          grep 'DOMAIN-SUFFIX' adrules_no_comments.list | sed 's/^DOMAIN-SUFFIX,/\./' > temp_suffix.list || true

          echo "Content of temp_suffix.list (first 10 lines):"
          head -n 10 temp_suffix.list

      - name: Download and process reject.conf and surge2.txt
        run: |
          echo "Downloading reject.conf and surge2.txt..."
          curl -sSL "https://ruleset.skk.moe/List/domainset/reject.conf" -o reject_conf_downloaded.conf
          curl -sSL "https://anti-ad.net/surge2.txt" -o surge2.txt

          echo "Removing comment lines from reject.conf..."
          grep -v '^#' reject_conf_downloaded.conf > processed_reject_conf.conf || true
          echo "Removing comment lines from surge2.txt..."
          grep -v '^#' surge2.txt > processed_surge2.txt || true

          echo "Content of processed_reject_conf.conf (first 10 lines):"
          head -n 10 processed_reject_conf.conf
          echo "Content of processed_surge2.txt (first 10 lines):"
          head -n 10 processed_surge2.txt

      - name: Merge files and remove duplicates
        run: |
          echo "Merging temp_suffix.list, processed_reject_conf.conf, and processed_surge2.txt..."
          cat temp_suffix.list processed_reject_conf.conf processed_surge2.txt | sort | uniq > source/reject.conf
          echo "Content of source/reject.conf (first 10 lines):"
          head -n 10 source/reject.conf

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add source/reject.conf source/reject_extra.list
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update reject files"
            git push
          else
            echo "No changes to commit"
          fi
