name: Update reject.conf

on:
  schedule:
    # 每天北京时间 0 点执行，UTC 时间为前一天16:00
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  update-reject-conf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v2

      - name: 配置 Git 用户信息
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: 下载、处理并合并文件
        run: |
          set -e
          mkdir temp && cd temp

          # 定义检测函数
          check_file() {
            if grep -qi "<html" "$1"; then
              echo "❌ 下载失败：$1 内容疑似 HTML，停止执行"
              head -n 20 "$1"
              exit 1
            fi
          }

          # 定义下载函数（自动重试3次）
          download() {
            local url=$1
            local output=$2
            local attempt=1
            local max_attempts=3
            local delay=5
            while [ $attempt -le $max_attempts ]; do
              echo "⬇️ 正在下载: $url (尝试 $attempt/$max_attempts)"
              if curl -sL --fail -o "$output" "$url"; then
                check_file "$output"
                echo "✅ 下载成功: $output"
                return 0
              else
                echo "⚠️ 下载失败: $url"
              fi
              attempt=$((attempt+1))
              if [ $attempt -le $max_attempts ]; then
                echo "⏳ 等待 $delay 秒后重试..."
                sleep $delay
              fi
            done
            echo "❌ 多次下载失败: $url"
            exit 1
          }

          # 下载并处理
          download https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list adrules.list
          grep "DOMAIN-SUFFIX," adrules.list | sed 's/DOMAIN-SUFFIX,/\./' > adrules_processed.txt

          download https://ruleset.skk.moe/List/domainset/reject.conf reject1.conf
          grep -v "^#" reject1.conf > reject1_processed.txt

          download https://anti-ad.net/surge2.txt surge2.txt
          grep -v "^#" surge2.txt > surge2_processed.txt

          # 合并去重
          cat adrules_processed.txt reject1_processed.txt surge2_processed.txt | sort -u > merged.txt

          # 统计行数并写入 reject.conf
          LINE_COUNT=$(wc -l < merged.txt)
          echo "# Total lines: ${LINE_COUNT}" > reject.conf
          cat merged.txt >> reject.conf

          # 生成 reject_clash.txt
          cp reject.conf reject_clash.txt
          sed -i 's/^\./+&/' reject_clash.txt

          # 移动到 source 文件夹
          mv reject.conf ../source/reject.conf
          mv reject_clash.txt ../source/reject_clash.txt

          # 清理临时目录
          cd ..
          rm -rf temp

      - name: 提交并推送更改
        run: |
          git add source/reject.conf source/reject_clash.txt
          git commit --allow-empty -m "Update reject.conf and reject_clash.txt"
          git push origin master
